version: "3.8"
services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
      # NOTE: Do not add real API keys here if cloning to public repo.
      # Set credentials in n8n UI after starting the instance.
    volumes:
      - ./n8n_data:/home/node/.n8n
